import type { CountryCode, StandAddress, StandAddressFields } from './types'

/**
 * Адресная книга пользователя с сохранёнными адресами.
 *
 * Состав одинаковый во всех странах — так концепты сравниваются на равных:
 *
 *   4 адреса курьерской доставки: 3 платных и 1 бесплатный;
 *   3 пункта выдачи: 2 бесплатных и 1 платный;
 *   1 офис компании, бесплатно.
 *
 * Восемь карточек — список не помещается на экран целиком, приходится
 * прокручивать и сравнивать. Это и проверяем: как человек выбирает из
 * восьми, а не из двух.
 *
 * Платные и бесплатные варианты есть и у курьера, и у пункта выдачи.
 * Без этого цена не участвует в выборе вообще: все курьерские стоят
 * одинаково, все пункты бесплатны — и сравнивать нечего.
 *
 * Форматы адресов, имена и телефоны — местные. Респондент должен читать
 * карточку как свою, иначе проверяется не интерфейс, а способность
 * разобрать чужой формат адреса.
 */

/**
 * Значения полей адреса. Ключи совпадают с FieldKey — это те же поля,
 * которые отдаёт useStandFields, только уже заполненные.
 *
 * Заполнены ровно те, что есть в форме этой страны: в России — подъезд,
 * этаж и домофон, в США — штат. Лишние остаются пустыми и в форму
 * не попадают.
 */
function fields(
  street: string,
  apartment: string,
  postal: string,
  city: string,
  extra: Partial<StandAddressFields> = {},
): StandAddressFields {
  return {
    addressLabel: 'home',
    street,
    apartment,
    entrance: '',
    floor: '',
    intercom: '',
    postal,
    city,
    region: '',
    comment: '',
    ...extra,
  }
}

export const addressBook: Record<CountryCode, StandAddress[]> = {
  ru: [
    {
      id: 'ru-courier-berezovoy',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      badgeKey: 'address.badge.last',
      recipientName: 'Иванов Иван Иванович',
      phone: '+7 999 111-22-33',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'проспект Берёзовой Рощи, 12, кв. 45, Москва, 125252',
      address: fields('Москва, проспект Берёзовой Рощи, 12', '45', '125252', 'Москва', {
        entrance: '2',
        floor: '5',
        intercom: '45К',
        comment: 'Код от подъезда 1234',
      }),
      price: 1349,
    },
    {
      id: 'ru-courier-leningradsky',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Иванова Мария Петровна',
      phone: '+7 999 222-33-44',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'Ленинградский проспект, 80, кв. 12, Москва, 125315',
      address: fields('Москва, Ленинградский проспект, 80', '12', '125315', 'Москва', {
        addressLabel: 'work',
        entrance: '1',
        floor: '3',
      }),
      price: 1349,
    },
    {
      id: 'ru-courier-kutuzovsky',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Петров Сергей Николаевич',
      phone: '+7 999 333-44-55',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'Кутузовский проспект, 24, кв. 3, Москва, 121165',
      address: fields('Москва, Кутузовский проспект, 24', '3', '121165', 'Москва', {
        addressLabel: 'custom',
        entrance: '4',
        floor: '2',
        intercom: '3В',
      }),
      price: 1349,
    },
    {
      id: 'ru-point-cdek',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Иванов Иван Иванович',
      phone: '+7 999 111-22-33',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'ул. Академика Виноградова, 5, Москва, 117133',
      pickupPointId: 'ru-cdek-vinogradova',
      price: 0,
    },
    {
      id: 'ru-point-fivepost',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Иванов Иван Иванович',
      phone: '+7 999 111-22-33',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'Варшавское шоссе, 132, Москва, 117405',
      pickupPointId: 'ru-fivepost-varshavskoe',
      price: 0,
    },
    {
      id: 'ru-office',
      method: 'pickup',
      methodKey: 'delivery.method.office',
      recipientName: 'Иванов Иван Иванович',
      phone: '+7 999 111-22-33',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'Хорошевское шоссе, 32к2, Москва, 123007',
      pickupPointId: 'ru-office-horoshevskoe',
      price: 0,
    },
    {
      id: 'ru-courier-profsoyuznaya',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Иванов Иван Иванович',
      phone: '+7 999 111-22-33',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'Профсоюзная улица, 104, кв. 77, Москва, 117321',
      address: fields('Москва, Профсоюзная улица, 104', '77', '117321', 'Москва', {
        entrance: '1',
        floor: '9',
      }),
      price: 0,
    },
    {
      id: 'ru-point-cdek-paid',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Иванов Иван Иванович',
      phone: '+7 999 111-22-33',
      email: 'qa.auto.checkout+ru@example.com',
      city: 'Москва',
      addressLine: 'ул. Руднёвка, 14, Москва, 111672',
      pickupPointId: 'ru-cdek-rudnevka',
      price: 199,
    },
  ],

  kz: [
    {
      id: 'kz-courier-abaya',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      badgeKey: 'address.badge.last',
      recipientName: 'Ахметов Данияр Маратович',
      phone: '+7 701 111-22-33',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'ул. Абая, 150, кв. 25, Алматы, 050009',
      address: fields('Алматы, ул. Абая, 150', '25', '050009', 'Алматы', {
        entrance: '3',
        floor: '7',
        intercom: '25',
      }),
      price: 2500,
    },
    {
      id: 'kz-courier-dostyk',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Смагулова Айгуль Ерлановна',
      phone: '+7 701 222-33-44',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'пр. Достык, 89, кв. 14, Алматы, 050051',
      address: fields('Алматы, пр. Достык, 89', '14', '050051', 'Алматы', {
        addressLabel: 'work',
        entrance: '1',
        floor: '4',
      }),
      price: 2500,
    },
    {
      id: 'kz-courier-zhandosova',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Ким Сергей Владимирович',
      phone: '+7 701 333-44-55',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'ул. Жандосова, 58, кв. 7, Алматы, 050035',
      address: fields('Алматы, ул. Жандосова, 58', '7', '050035', 'Алматы', {
        addressLabel: 'custom',
        floor: '2',
      }),
      price: 2500,
    },
    {
      id: 'kz-point-cdek',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Ахметов Данияр Маратович',
      phone: '+7 701 111-22-33',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'пр. Райымбека, 212, Алматы, 050014',
      pickupPointId: 'kz-cdek-raiymbek',
      price: 0,
    },
    {
      id: 'kz-point-kazpost',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Ахметов Данияр Маратович',
      phone: '+7 701 111-22-33',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'ул. Богенбай батыра, 132, Алматы, 050000',
      pickupPointId: 'kz-kazpost-bogenbay',
      price: 0,
    },
    {
      id: 'kz-office',
      method: 'pickup',
      methodKey: 'delivery.method.office',
      recipientName: 'Ахметов Данияр Маратович',
      phone: '+7 701 111-22-33',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'пр. Аль-Фараби, 77/7, Алматы, 050040',
      pickupPointId: 'kz-office-alfarabi',
      price: 0,
    },
    {
      id: 'kz-courier-samal',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Ахметов Данияр Маратович',
      phone: '+7 701 111-22-33',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'мкр. Самал-2, 33, кв. 18, Алматы, 050051',
      address: fields('Алматы, мкр. Самал-2, 33', '18', '050051', 'Алматы', {
        entrance: '2',
        floor: '6',
      }),
      price: 0,
    },
    {
      id: 'kz-point-cdek-paid',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Ахметов Данияр Маратович',
      phone: '+7 701 111-22-33',
      email: 'qa.auto.checkout+kz@example.com',
      city: 'Алматы',
      addressLine: 'ул. Абая, 68, Алматы, 050008',
      pickupPointId: 'kz-cdek-abaya',
      price: 500,
    },
  ],

  de: [
    {
      id: 'de-courier-kastanienallee',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      badgeKey: 'address.badge.last',
      recipientName: 'Anna Schmidt',
      phone: '+49 151 1112233',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Kastanienallee 42, 10435 Berlin',
      address: fields('Kastanienallee 42', '3. OG', '10435', 'Berlin'),
      price: 4.9,
    },
    {
      id: 'de-courier-friedrichstrasse',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Michael Weber',
      phone: '+49 151 2223344',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Friedrichstraße 120, 10117 Berlin',
      address: fields('Friedrichstraße 120', '', '10117', 'Berlin'),
      price: 4.9,
    },
    {
      id: 'de-courier-karl-marx-allee',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Julia Becker',
      phone: '+49 151 3334455',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Karl-Marx-Allee 78, 10243 Berlin',
      address: fields('Karl-Marx-Allee 78', '12', '10243', 'Berlin'),
      price: 4.9,
    },
    {
      id: 'de-point-packstation-128',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Anna Schmidt',
      phone: '+49 151 1112233',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Packstation 128, Prenzlauer Allee 90, 10409 Berlin',
      pickupPointId: 'de-dhl-packstation-128',
      price: 0,
    },
    {
      id: 'de-point-packstation-215',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Anna Schmidt',
      phone: '+49 151 1112233',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Packstation 215, Danziger Straße 12, 10435 Berlin',
      pickupPointId: 'de-dhl-packstation-215',
      price: 0,
    },
    {
      id: 'de-office',
      method: 'pickup',
      methodKey: 'delivery.method.office',
      recipientName: 'Anna Schmidt',
      phone: '+49 151 1112233',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Kurfürstendamm 194, 10707 Berlin',
      pickupPointId: 'de-office-kurfuerstendamm',
      price: 0,
    },
    {
      id: 'de-courier-schoenhauser',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Anna Schmidt',
      phone: '+49 151 1112233',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Schönhauser Allee 36, 10435 Berlin',
      address: fields('Schönhauser Allee 36', '2. OG', '10435', 'Berlin'),
      price: 0,
    },
    {
      id: 'de-point-packstation-paid',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Anna Schmidt',
      phone: '+49 151 1112233',
      email: 'qa.auto.checkout+de@example.com',
      city: 'Berlin',
      addressLine: 'Packstation 407, Schönhauser Allee 118, 10439 Berlin',
      pickupPointId: 'de-dhl-packstation-407',
      price: 2.9,
    },
  ],

  pl: [
    {
      id: 'pl-courier-marszalkowska',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      badgeKey: 'address.badge.last',
      recipientName: 'Anna Kowalska',
      phone: '+48 501 111 222',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'ul. Marszałkowska 84/92 m. 15, 00-514 Warszawa',
      address: fields('ul. Marszałkowska 84/92', 'm. 15', '00-514', 'Warszawa'),
      price: 19.9,
    },
    {
      id: 'pl-courier-pulawska',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Piotr Nowak',
      phone: '+48 501 222 333',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'ul. Puławska 42 m. 8, 02-508 Warszawa',
      address: fields('ul. Puławska 42', 'm. 8', '02-508', 'Warszawa'),
      price: 19.9,
    },
    {
      id: 'pl-courier-jerozolimskie',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Magdalena Wiśniewska',
      phone: '+48 501 333 444',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'al. Jerozolimskie 123 m. 30, 02-017 Warszawa',
      address: fields('al. Jerozolimskie 123', 'm. 30', '02-017', 'Warszawa'),
      price: 19.9,
    },
    {
      id: 'pl-point-waw01m',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Anna Kowalska',
      phone: '+48 501 111 222',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'Paczkomat WAW01M, ul. Nowogrodzka 50, 00-695 Warszawa',
      pickupPointId: 'pl-inpost-waw01m',
      price: 0,
    },
    {
      id: 'pl-point-waw42a',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Anna Kowalska',
      phone: '+48 501 111 222',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'Paczkomat WAW42A, ul. Grójecka 194, 02-390 Warszawa',
      pickupPointId: 'pl-inpost-waw42a',
      price: 0,
    },
    {
      id: 'pl-office',
      method: 'pickup',
      methodKey: 'delivery.method.office',
      recipientName: 'Anna Kowalska',
      phone: '+48 501 111 222',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'ul. Domaniewska 37, 02-672 Warszawa',
      pickupPointId: 'pl-office-domaniewska',
      price: 0,
    },
    {
      id: 'pl-courier-krucza',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Anna Kowalska',
      phone: '+48 501 111 222',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'ul. Krucza 16/22 m. 4, 00-526 Warszawa',
      address: fields('ul. Krucza 16/22', 'm. 4', '00-526', 'Warszawa'),
      price: 0,
    },
    {
      id: 'pl-point-inpost-paid',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Anna Kowalska',
      phone: '+48 501 111 222',
      email: 'qa.auto.checkout+pl@example.com',
      city: 'Warszawa',
      addressLine: 'Paczkomat WAW77B, ul. Wilcza 35, 00-544 Warszawa',
      pickupPointId: 'pl-inpost-waw77b',
      price: 9.9,
    },
  ],

  cz: [
    {
      id: 'cz-courier-vinohradska',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      badgeKey: 'address.badge.last',
      recipientName: 'Jana Nováková',
      phone: '+420 601 111 222',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Vinohradská 112, 130 00 Praha 3',
      address: fields('Vinohradská 112', 'byt 9', '130 00', 'Praha'),
      price: 99,
    },
    {
      id: 'cz-courier-korunni',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Petr Svoboda',
      phone: '+420 601 222 333',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Korunní 58, 120 00 Praha 2',
      address: fields('Korunní 58', '', '120 00', 'Praha'),
      price: 99,
    },
    {
      id: 'cz-courier-sokolovska',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Lucie Dvořáková',
      phone: '+420 601 333 444',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Sokolovská 200, 190 00 Praha 9',
      address: fields('Sokolovská 200', 'byt 4', '190 00', 'Praha'),
      price: 99,
    },
    {
      id: 'cz-point-belehradska',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Jana Nováková',
      phone: '+420 601 111 222',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Zásilkovna, Bělehradská 45, 120 00 Praha 2',
      pickupPointId: 'cz-zasilkovna-belehradska',
      price: 0,
    },
    {
      id: 'cz-point-ceskomoravska',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Jana Nováková',
      phone: '+420 601 111 222',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Zásilkovna, Českomoravská 2420, 190 00 Praha 9',
      pickupPointId: 'cz-zasilkovna-ceskomoravska',
      price: 0,
    },
    {
      id: 'cz-office',
      method: 'pickup',
      methodKey: 'delivery.method.office',
      recipientName: 'Jana Nováková',
      phone: '+420 601 111 222',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Na Příkopě 22, 110 00 Praha 1',
      pickupPointId: 'cz-office-naprikope',
      price: 0,
    },
    {
      id: 'cz-courier-karlovo',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Jana Nováková',
      phone: '+420 601 111 222',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Karlovo náměstí 10, 120 00 Praha 2',
      address: fields('Karlovo náměstí 10', 'byt 6', '120 00', 'Praha'),
      price: 0,
    },
    {
      id: 'cz-point-zasilkovna-paid',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'Jana Nováková',
      phone: '+420 601 111 222',
      email: 'qa.auto.checkout+cz@example.com',
      city: 'Praha',
      addressLine: 'Zásilkovna, Karlovo náměstí 24, 120 00 Praha 2',
      pickupPointId: 'cz-zasilkovna-karlovo',
      price: 49,
    },
  ],

  us: [
    {
      id: 'us-courier-fifth-avenue',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      badgeKey: 'address.badge.last',
      recipientName: 'John Miller',
      phone: '+1 212 111 2233',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: '350 5th Ave, Apt 21B, New York, NY 10118',
      address: fields('350 5th Ave', 'Apt 21B', '10118', 'New York', { region: 'NY' }),
      price: 6.99,
    },
    {
      id: 'us-courier-astor-place',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'Sarah Johnson',
      phone: '+1 212 222 3344',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: '1 Astor Pl, Apt 5C, New York, NY 10003',
      address: fields('1 Astor Pl', 'Apt 5C', '10003', 'New York', { region: 'NY' }),
      price: 6.99,
    },
    {
      id: 'us-courier-west-57th',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'David Brown',
      phone: '+1 212 333 4455',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: '200 W 57th St, Apt 12A, New York, NY 10019',
      address: fields('200 W 57th St', 'Apt 12A', '10019', 'New York', { region: 'NY' }),
      price: 6.99,
    },
    {
      id: 'us-point-farley',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'John Miller',
      phone: '+1 212 111 2233',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: 'USPS James A. Farley Station, 421 8th Ave, New York, NY 10001',
      pickupPointId: 'us-usps-farley',
      price: 0,
    },
    {
      id: 'us-point-cooper',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'John Miller',
      phone: '+1 212 111 2233',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: 'USPS Cooper Station, 93 4th Ave, New York, NY 10003',
      pickupPointId: 'us-usps-cooper',
      price: 0,
    },
    {
      id: 'us-office',
      method: 'pickup',
      methodKey: 'delivery.method.office',
      recipientName: 'John Miller',
      phone: '+1 212 111 2233',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: '1120 Avenue of the Americas, New York, NY 10036',
      pickupPointId: 'us-office-sixth-avenue',
      price: 0,
    },
    {
      id: 'us-courier-west-34th',
      method: 'courier',
      methodKey: 'delivery.method.courier',
      recipientName: 'John Miller',
      phone: '+1 212 111 2233',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: '15 W 34th St, Apt 8D, New York, NY 10001',
      address: fields('15 W 34th St', 'Apt 8D', '10001', 'New York', { region: 'NY' }),
      price: 0,
    },
    {
      id: 'us-point-usps-paid',
      method: 'pickup',
      methodKey: 'delivery.method.point',
      recipientName: 'John Miller',
      phone: '+1 212 111 2233',
      email: 'qa.auto.checkout+us@example.com',
      city: 'New York',
      addressLine: 'USPS Midtown Station, 340 W 42nd St, New York, NY 10036',
      pickupPointId: 'us-usps-madison',
      price: 3.99,
    },
  ],
}
